### ISSUE TITLE
Cant run 

### ISSUE THREAD

**Issue by bubobih** [hellzerg/optimizer#10]
In last windows updates exe got suspended in task and he doesent run...

**Comment by hellzerg** [comment]
The most compatible version of Windows 10 for Optimizer is build 1607, but it has been tested up to build 1809.
I currently stopped developing it, because with every new build, MS just destroys the functionality and it needs research again and again. Just so tiresome.

Also, note that, disabling Privacy Options (camera, mic, etc) in newer builds, traditional desktop apps that are using camera & mic will be rendered useless. You need not disable their permissions.
