### ISSUE TITLE
OneDrive not working any more + All files are gone

### ISSUE THREAD

**Issue by PixxInc** [hellzerg/optimizer#105]
I used the program to disable Start Menu Ads and Cortana. After I did that, the program hung and all my files(OneDrive files [Desktop/Files/Videos ...]) were gone. The recycle bin was empty, and I can't restore the files with e.g. Disk Drill either. I can no longer open OneDrive (nothing happens when I open it).

I'm pretty sure I didn't press the Uninstall OneDrive button, but if I did, is there any way to get the files back?

Thanks for the help ~ Pixx

**Comment by hellzerg** [comment]
Your files are on cloud storage intact, right?
If you pressed Uninstall OneDrive, revert it back.

**Comment by PixxInc** [comment]
What do you mean?
When I open the program the uninstall onedrive switch is set to off. Reinstalling Onedrive doesn't help either, because it still won't open.

**Comment by hellzerg** [comment]
https://windowsloop.com/reinstall-onedrive-on-windows-10/#cmd

If you try to reinstall it using Command Prompt, what will gonna happen?

**Comment by PixxInc** [comment]
OneDrive installs normally, but still does not open.

**Comment by hellzerg** [comment]
I recommend that you enable Uninstall OneDrive in app, then restart your PC, and last one, revert it back.

**Comment by pufidori** [comment]
never doing anything like this again. totally destroyed my computer

**Comment by Jisll** [comment]
> never doing anything like this again. totally destroyed my computer

You should operate functions if you know what they do, if you use OneDrive, and uninstall it, then this Program is not to blame, but you, we try for users to let remove some functions to possibly more performance or also to eliminate unnecessary things, e.g. I do not use widgets, so I removed it. But if you use OneDrive, and uninstall it, then clearly the PC is "in the bucket".... Since all useful files are stored on OneDrive.
