### ISSUE TITLE
Will this effect my pc?

### ISSUE THREAD

**Issue by beaste69** [hellzerg/optimizer#222]
In long run for my laptop do this effects anything?? like battery or slows the pc?

**Comment by staurosKaragiannis** [comment]
This program basically gives you the ability to disable certain features. So by disabling a featue, you may optimize your computer BUT you wont be able to use that anymore until you enable it again. 

So to answer your question, i don't think that disabling a feature will slow down your PC or affect your battery in any negative way but it will affect it in a positive one, which is why its called "optimizer"

**Comment by hellzerg** [comment]
Exactly as @staurosKaragiannis have told you.
There is no danger of lowering your battery.
