### ISSUE TITLE
Found Trojan and mucho more

### ISSUE THREAD

**Issue by mondipr** [hellzerg/optimizer#306]
MD5	0acd5fdeb1332e99679f9c5403fd5dbe
I uploading the file to different web analyze software.
https://tria.ge/230311-rckmgahg89/behavioral1
![image](https://user-images.githubusercontent.com/5105138/224490764-20f71cda-a2e6-49df-a890-73c50a2cf4c4.png)
http://www.hybrid-analysis.com/sample/cc81be39adcb8ea105c75106084f7b6809014aede70b52fd7eb2f41d5c7c288c

![image](https://user-images.githubusercontent.com/5105138/224491110-578e59e2-e8c5-4e50-8739-30d35c0b1966.png)
https://www.virustotal.com/gui/file/cc81be39adcb8ea105c75106084f7b6809014aede70b52fd7eb2f41d5c7c288c

https://www.filescan.io/uploads/640c9152c7fa23d27f72d7d8/reports/170d36d6-fbb0-451d-9555-a481aa2a11e3/overview
![image](https://user-images.githubusercontent.com/5105138/224491151-d6fd728e-e0ba-4c73-bf3f-8ae264e8aa63.png)
Why all this page found a trojan? Who explain this?

**Comment by vadiscode** [comment]
Of course, and there's nothing surprising about that either. In this type of programs (which work with your registry and system files) any anti-virus will think it is a virus, and this is logical because it modifies your system settings and registry, but in this case you should not fear this because the program is completely open source.

**Comment by hellzerg** [comment]
@mondipr 

As @vadiscode has already said. The software is completely safe. All these detections are false positives.

**Comment by mondipr** [comment]
OK... Thanks for that.
