### ISSUE TITLE
The checkbox is very misleading

### ISSUE THREAD

**Issue by visualwind** [hellzerg/optimizer#341]
I dont know if one item is optimized. 
For example, I disabled windows search service with other software. the checkbox is gray, not active. 
I dont know if it is dowe

**Comment by hellzerg** [comment]
It's impossible to check all these things if they are active or not on the system.

Also, it's recommended not to use anything similar before using Optimizer.

Because it has fine-grain control over the specifics of each option it provides.

Many problems that users had in the past were in fact not by Optimizer itself but because some other app didn't remove the configs it applied when the user tried to uninstall or reset it.

Have in mind all these factors.

@visualwind
