### ISSUE TITLE
What is meant by 'Disable privacy options'?

### ISSUE THREAD

**Issue by TontyTon** [hellzerg/optimizer#4]
Hey, Thanks for this wonderful program.
Would you please add a file which explains what a particular option does or reference to site from which tweaks are imported?
Especially explain-
- Disable privacy options 
- Disable sensor services

**Comment by hellzerg** [comment]
Hello

- Disable Sensor Services:

It disables various Windows services that are responsible for sensors to work.
Tablet devices with Windows have these sensors, so disabling them will render auto-brightness, auto-rotation etc useless.
But if you have a desktop machine, disabling them is safe

- Disable Privacy Options:

It switches to OFF the various privacy options (toggles) in Settings > Privacy section.
Well, with every major Windows update, the corresponding registry keys change, that's why I can't keep it up-to-date every time.
Actually, the last 'compatible' build is 1607, it disables almost everything in that build.
