### ISSUE TITLE
Wifi not working after after using Optimizer 

### ISSUE THREAD

**Issue by TekhU** [hellzerg/optimizer#445]
### My wifi seems to not work after using Optimizer.
I used Optimizer for uninstalling some software and disabling telemetry I believe. Shortly after restarting my Laptop to apply changes, I discover that I couldn't connect to any wifi connections. It says that "Can't connect to this network". I've changed and restart my Laptop countless time yet the same problem persist. I've tried reinstalling my wifi adapter driver and even wiping clean my laptop but the same problem carries over.
I decided to reinstall windows completely and change to a new storage SSD and it worked, but after testing this new window and running Optimizer again to uninstall package, the same bug appeared and happened again to my laptop. I'm now stuck with using a wireless wifi USB to connect.

![image_2023-12-14_135125811](https://github.com/hellzerg/optimizer/assets/70067268/d018b90b-ce24-49a1-a97c-d87c2f9e642c)

Here is my wifi adapter
![image_2023-12-14_134911875](https://github.com/hellzerg/optimizer/assets/70067268/440dfc01-df6b-4085-ae8c-a5d21e1611ef)

**Comment by hellzerg** [comment]
@TekhU 

Did you touch anything in the Network tab, regarding DNS options etc?

**Comment by TekhU** [comment]
> @TekhU
> 
> Did you touch anything in the Network tab, regarding DNS options etc?

No I didnt touch it before the issue happened. I think I tried to clear the DNS cache after I got the problem but it didnt do anything.

**Comment by hellzerg** [comment]
@TekhU Did you fix the problem?

**Comment by dcooper-database9** [comment]
I encounter this from time to time, and it usually is caused by Windows updates.  Microsoft often pushes out driver updates that create more problems than they fix.  That driver was rolled out by Microsoft in July of 2023 and it may have just been installed.  I would check with Realtek and install their latest driver.  Then you need to tell Windows not to update drivers when it updates the OS.

Another glitch I often run into happens after a Windows update has installed.  If it wants you to restart and you don't, it will sometimes disable the network connections until you do.

If you're starting with a clean install of Windows make sure it's completely updated before you fiddle with settings.  I usually find that after I setup a new computer it will download updates in the background, requiring two or three restarts before it completely finishes.
