### ISSUE TITLE
Exclude Drivers from Windows Update is not working

### ISSUE THREAD

**Issue by guzelonur** [hellzerg/optimizer#76]
Nice project, however, even when you set such "ExcludeWUDriversInQualityUpdate" registry key value to 1, it does NOT work with Windows 10 21H1 Home edition at all, the setting is simply ignored and unwanted drivers are being pushed forcefully by Windows Update. I haven't tried with Pro, but my friend says the same effect with 21H1 Pro. Same result when done through Optimizer GUI, as expected. It must be Microsoft's another annoying obligation to take our driver installation freedom back.

**Comment by hellzerg** [comment]
According to this: https://answers.microsoft.com/en-us/windows/forum/all/stop-driver-auto-installation/bdbf8f98-81e8-4482-9002-ce469cf6568a 

Home edition ignores the registry keys. Probably Microsoft did the same for Pro edition as well.
So, yeah, again Microsoft ignoring custom configuration, because "these settings should apply only to business setups".

**Comment by guzelonur** [comment]
@hellzerg many thanks for your reply. I surfed almost all the resources on the internet regarding to this undocumented issue, and finally concluded that enormous amount of articles are either outdated or incorrect which are saying "If you're running on Home edition, use registry method to set GPO setting as well", which is wrong. 

Additionally, I consider Pro edition as Business as it should be in my opinion which has built-in GPO editor providing such Group Policy settings for every need, including exclusion of drivers from Windows Update. 

Or does Microsoft refer to Enterprise or LTSB/LTSC or Workstation editions by means of "Business"? It is not clear.

It is really insane and a real nightmare not having any control over my OS environment eventhough having Pro.

**Comment by hellzerg** [comment]
@guzelonur Yes, vast amount of registry tweaks have been working properly, but then at some point have been rendered useless by Microsoft, from build to build. 

I remember myself hunting down tweaks again and again from the very first RTM build of Windows 10 (1507), and with every new build since then, keys/tweaks are constantly changing and/or ignored.

Windows 10 and 11 service model is a terrible, terrible nightmare.

**Comment by hellzerg** [comment]
@guzelonur How many people are doing similar projects to mine and with each new build they develop fatigue and then they abandon the project.

Exactly that will happen to my case too, some day.

**Comment by guzelonur** [comment]
Friend, indeed there are many similar projects like yours, but your work is really valuable as long as and it seems that you know what you're coding and doing. But as you stated, Microsoft started a war even against advanced users and geeks changing/ignoring every detail by disallowing 'any' control over my own systems, and they're doing this not only from build to build, also from update to update. They are also doing this silently and many articles remain invalid on the internet as they are no longer applicable, like in this case registry tweaks. I miss Windows 7 which obeys the settings exactly what user have set, Windows 10 is another universe and has no respect to user at all, this is the awful truth.

**Comment by thunderpants** [comment]
Very nice program hellzerg ,thanks for sharing with us !
